pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Forge'
			url = 'https://maven.minecraftforge.net/'
		}
		maven {
			name = 'NeoForged'
			url = 'https://maven.neoforged.net/releases'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

includeBuild('screenplay-gradle-plugin')
// Isolate Forge/NeoGradle from Fabric Loom runs (NeoGradle treats custom Loom run names as run types).
includeBuild('screenplay-loaders') {
	dependencySubstitution {
		substitute module('com.adamkali.screenplay:screenplay-forge') using project(':forge')
		substitute module('com.adamkali.screenplay:screenplay-neoforge') using project(':neoforge')
	}
}
includeBuild('dwm-loaders')

include 'dwm-common'
include 'screenplay-common'
include 'screenplay-fabric'

rootProject.name = 'dwm'
