version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1.2

jobs:
  run-gradle:
    parameters:
      gradle_command:
        type: string
        default: ""
    docker:
      - image: cimg/openjdk:21.0
    environment:
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      - run:
          name: Run Gradle Command
          command: |
            chmod +x ./gradlew
            ./gradlew << parameters.gradle_command >>

  update-version:
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run:
          name: Upload version.json to S3
          command: |
              aws s3 cp version.json s3://modding/dwm/version.json


workflows:
  build-and-test:
    jobs:
      - run-gradle:
          name: Build
          gradle_command: "build"
      - run-gradle:
          name: Test
          gradle_command: "test"

  build-and-publish:
    jobs:
      - update-version
      - run-gradle:
          filters:
            branches:
              only:
                - main