version: 2.1

jobs:
  publish:
    machine:
      image: ubuntu-2204:2024.08.1
    environment:
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - setup
      - run: |
          chmod +x ./gradlew
          ./gradlew publish

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-publish:
    jobs:
      - publish